/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as RunRunIdImport } from "./routes/run.$runId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const RunRunIdRoute = RunRunIdImport.update({
  id: "/run/$runId",
  path: "/run/$runId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/run/$runId": {
      id: "/run/$runId";
      path: "/run/$runId";
      fullPath: "/run/$runId";
      preLoaderRoute: typeof RunRunIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/run/$runId": typeof RunRunIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/run/$runId": typeof RunRunIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/run/$runId": typeof RunRunIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/run/$runId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/run/$runId";
  id: "__root__" | "/" | "/run/$runId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RunRunIdRoute: typeof RunRunIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunRunIdRoute: RunRunIdRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/run/$runId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/run/$runId": {
      "filePath": "run.$runId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
